package worker;

public enum State {

    UNKNOWN,
    INITIALIZING,
    AWAITING_TRANSACTION,
    TRANSACTION_RECEIVED,
    VALIDATING_TRANSACTION,
    AWAITING_TRANSACTION_APPROVAL,
    MINING_BLOCK,
    BLOCK_FOUND,
    AWAITING_BLOCK_APPROVAL;

}
